import type { Metadata } from "next";
import "./globals.css";
import {PropsWithChildren} from "react";

export const metadata: Metadata = {

	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {

	return (

		<html lang="fr">

			<body>

				{children}
			</body>
		</html>
	);
}
